build.train:
	docker compose -f docker-compose-train.yaml up --build -d

start.train:
	docker compose -f docker-compose-train.yaml up -d

down.train:
	docker compose -f docker-compose-train.yaml down -v