GPU_NUM: "0"

mode: "cls" # "cls", "all"

litmodel: "base" # "base", "weighted"
model: "shallowconvnet"
score: null # "pbs"
pruning_ratio: null # Only used when using hard rejection
weighted_loss: False
